### ISSUE TITLE
Trackpad issue using virtual desktop

### ISSUE THREAD

**Issue by TerminatedGA** [ClassicOldSong/Apollo#10]
After enabling virtual desktop in native samsung tab s9 ultra resolution (2980 x 1820), trackpad detection with the samsung keyboard cover becomes wacky, as it seems all trackpad movement becomes rotated by 90 degrees clockwise (top swipe becomes right movement, right swipe becomes down movement, etc). Am using Appolo and Artemis latest version.

**Comment by TerminatedGA** [comment]
Issue didnt resolve after going back to default 2k resolution in non-virtual display

**Comment by TerminatedGA** [comment]
Temporary fix: Removing keyboard cover, switching to tablet mode, use tablet mode briefly then switching back to keyboard cover trackpad again

**Comment by ClassicOldSong** [comment]
This seems to be an Samsung/Android issue, which apps can't fix

I have encountered similar issues on my OnePlus tablet in some native android apps like the Play Store, when sometimes trackpad clicks are rotated. Hope Android will fix this issue in the future.

**Comment by TerminatedGA** [comment]
Okay thank you!
