### ISSUE TITLE
启动moonlight/Artemis时，直接唤醒了局域网内的计算机

### ISSUE THREAD

**Issue by Zyeus** [ClassicOldSong/Apollo#103]
目前我会使用「雪藏」冻结游戏，然后休眠计算机来保证我下次可以快速继续之前的游戏。但当我用steam大屏模式休眠计算机后，只要回到 Artemis 主界面就会重新把计算机唤醒……只有在选择休眠后，立即杀掉 Artemis 进程才能防止唤醒。而且如果直接启动Artemis 的话，计算机也就自动唤醒了。不知道是不是哪里设置错了，预期情况是，点击计算机图标后选择wol后再唤醒计算机

**Comment by Aries2050** [comment]
请注意网卡设置允许唤醒计算机的数据包类型，应该设置为只允许幻数据包

**Comment by ClassicOldSong** [comment]
> 请注意网卡设置允许唤醒计算机的数据包类型，应该设置为只允许幻数据包

这个应该是正解。

这也不是Apollo的问题，这个issue先关了。
