### ISSUE TITLE
SudoVDA doesn't show virtual display in Windows settings

### ISSUE THREAD

**Issue by brentz123** [ClassicOldSong/Apollo#108]
On Windows 10 22H2, running clean Apollo install.

Device Manager shows "SudoMaker Virtual Display Adapter" & Apollo Config -> Audio/Video shows " SudoVDA Driver status: Ready". However, Windows Display settings do not show an active virtual display. I tested with the original [Virtual Display Driver](https://github.com/itsmikethetech/Virtual-Display-Driver) & was able to see a virtual display in Windows settings. 

Any advice on how to fix this? Is there something simple I'm missing?

**Comment by ClassicOldSong** [comment]
You need to start a stream with the `Virtual Desktop` entry. The virtual display isn't persistent, it's created on-demand.

Forget everything you knew about OG Sunshine and VDD, just explore Apollo from the very beginning.

**Comment by brentz123** [comment]
Thank you!

**Comment by fcakyon** [comment]
> You need to start a stream with the `Virtual Desktop` entry. 

What do you mean by that @ClassicOldSong? Can you give more details, please?

**Comment by ClassicOldSong** [comment]
Apollo has an dedicated virtual desktop entry with a logo showing a + sign. If you couldn't see that from your Artemis/Moonlight client, that means either you're not using Apollo or SudoVDA isn't loaded correctly.
