### ISSUE TITLE
Old bug from Sunshine still exist

### ISSUE THREAD

**Issue by namquang93** [ClassicOldSong/Apollo#11]
Looks like this old bug is still in the project. I got this bug when using Sunshine long time ago and they fixed it.

https://github.com/XITRIX/Moonlight-Switch/issues/145

![att lUwKHwfD1fU5O84yl04BIRANIAx1ZBTGBqxJbqJ3E8w](https://github.com/user-attachments/assets/754f894d-cd93-46da-b505-fdc9abb62319)

**Comment by ClassicOldSong** [comment]
This seems to be a result of dropped resolution advertisements (from upstream Sunshine) and seemingly only affecting older switch clients.

IIRC the switch client is working on with no resolution advertisements right now.

**Comment by ClassicOldSong** [comment]
I've just checked the server resolution check was removed in Moonlight-Switch 1.2.0 and the latest version is 1.2.1, can you update your client and try again?

**Comment by namquang93** [comment]
Thank you I didn't know this was fixed. Updating Moonlight-Switch to the latest version 1.2.1 solved the bug.
