### ISSUE TITLE
Check your firewall and port forwarding rules for ports: UDP 47998 and UDP 48000

### ISSUE THREAD

**Issue by dessigndiffuse** [ClassicOldSong/Apollo#112]
Hello, firstly thanks for this project with virtual display driver integrated.
I have seen same issue opened before but this time cause is different for me i think.
This only happens when resolution is set to match my phone's native resolution, all other default resolutions work , including 4K.

I did not see option to add advertised resolution like on sunshine maybe that is the problem ?

I have Native (2265x1080) and Native Full-Screen (3120x1440) options on my phone which dont work.

**Comment by ClassicOldSong** [comment]
That's something won't work. Some really weird resolution will cause the encoder fail to start, and all of them are resolutions with an odd numbered X value. Sometimes it works after a reboot or display driver update.

You can set resolution scaling up a bit to avoid this problem, as scaled resolution will always be capped off to the closest even numbers when creating the virtual display. Streaming resolution won't change though, so whether it'll work depends, but usually this bypasses the issue.

**Comment by dessigndiffuse** [comment]
Ah thank you indeed that custom resolution was wrong, i pulled the resolution from product page of phone but when i checked with an app it showed different  (2340x1080) which works now and fills the notch area as well, thanks!

**Comment by ajitid** [comment]
Hi @dessigndiffuse. I'm unable to figure out where I can set a custom resolution (I'm on Android). In Virtual-Display-Driver, I can set a resolution [in an XML](https://github.com/VirtualDisplay/Virtual-Display-Driver/wiki/How-to-configure-the-driver#resolutions-section) but I cannot figure out where I would do the same for SudoVDA. I would appreciate any help, thanks!

**Comment by ClassicOldSong** [comment]
You don't need to set any resolution manually. You just set your client's resolution to "Native Resolution" and start streaming.

**Comment by ajitid** [comment]
Thanks @ClassicOldSong for replying, but that gives a black screen with the same error that @dessigndiffuse was getting. That's why I want to use a lower custom resolution with the aspect ratio that matches my phone. I actually specified a resolution in Artemis > Settings > Custom Resolution but that didn't do anything; it seems to only affect actual displays and not the virtual one.

**Comment by ClassicOldSong** [comment]
If you just want a lower resolution, you can use Resolution Scale Factor option.

The first time you stream you need to go to Windows display settings and set display option to "Extended".

**Comment by ajitid** [comment]
All that is set correctly, and I just found my solution. Thanks for the help Yuniko! 

Here's I was wrong:
My mistake was that I expected when I set a "Custom Resolution" in Artemis' settings, it would be automatically applied. I was wrong there. I have to select this resolution in "Video resolution" too for it to be selected.
