### ISSUE TITLE
Jumbled desktop icons after disconnecting session. 

### ISSUE THREAD

**Issue by kripler7** [ClassicOldSong/Apollo#117]
Hello, just recently tried using Apollo after having been a Sunshine user for a while. I am noticing that whenever I quit a stream, all the icons on my main display are jumbled up or get pushed to one corner of the display. I did not experience this when using Sunshine. I have an Icon restorer app to mitigate this after each stream but it would be cool if this just didn't happen in the first place. Maybe Apollo can integrate a icon layout back up before starting a stream and then restoring it after the stream ends?

**Comment by ClassicOldSong** [comment]
Blame Windows for this issue, Apollo only creates and removes a virtual display when you stream/exit.

You should notice the same when you plug and remove a real display, but the way it messes up the desktop icons is new to me.

I use auto arrange icons and align to grid on my desktop so this might be the reason I'm not affected.

**Comment by ClassicOldSong** [comment]
> I have an Icon restorer app to mitigate this after each stream

You can launch the restorer in `UNDO` commands. As this is not an actual issue Apollo should care about, I'm closing it now.
