### ISSUE TITLE
Toggle mouse mode on Xbox client is not working

### ISSUE THREAD

**Issue by lyndonguitar** [ClassicOldSong/Apollo#126]
I know its not in the scope of this fork but I would like to report that when using Apollo Server paired with Xbox Client, 
"Toggle Mouse Mode" option does not work and I cannot control the desktop using the built-in mouse mode of Moonlight Xbox.

In the Apollo setting I have "Enable Mouse input" set to "Enabled" if that helps
![image](https://github.com/user-attachments/assets/7df90ada-adb0-4d2c-85fe-e58294f5e9de)

**Comment by ClassicOldSong** [comment]
Have you grant Mouse Input permission to your Xbox client? I can use mouse emulation with mine perfectly.

**Comment by Pijuli** [comment]
I might have the same issue with Android and Linux client too. Is just the left&right click unresponsive or the whole mouse emulation?

**Comment by theBeaz** [comment]
> Have you grant Mouse Input permission to your Xbox client? I can use mouse emulation with mine perfectly.

Just wanted to second this. One of my clients is the Xbox client (which got me to switch to Apollo) and mouse control works just fine. I have to enable it every time so that I can clear the screensaver... so thankfully it does indeed work!

**Comment by lyndonguitar** [comment]
> Have you grant Mouse Input permission to your Xbox client? I can use mouse emulation with mine perfectly.

thank you. that was the solution to the problem. Its neat that you can set permissions per device btw, i dont remember Sunshine having this feature. I moved on from Sunshine to Apollo last month and loving it.

PS. I hope you also eventually make an Artemis/Apollo client for Xbox in the future. With better features like frame pacing/ALLM support. 🙏 . Awesome work

**Comment by ClassicOldSong** [comment]
Glad it solved your problem!

I don't have that much time and Xbox might not be able to implement advanced features like frame pacing due to UWP limitations.
