### ISSUE TITLE
Issue with uasage of Dual Monitor

### ISSUE THREAD

**Issue by motsch94** [ClassicOldSong/Apollo#127]
Hello,

I have a issue with Apollo.
I try to connect to my VM Windows 10 with Moonlight/Apollo.
With 1 Monitor all is working fine. 
But for me the FAQ "How to start multiple instances of Apollo" is not working.

_"3. Start the second Apollo instance:
Once the configuration file is ready, start the second Apollo instance by running:
sunshine.exe path\to\sunshine_2.conf
Make sure you run it with SYSTEM privilege to ensure full functionality."_

How does i run the second instance under Windows 10? I dont know how.
I tryed to modify the shortcut Apollo in Windows Start menu. But it didnt work.
Can anyone please explain me how?
And the start-apollo.ps1 is also not working. Powershell cloeses himselv quickly.

Sorry for my bad english.
And thank you for the nice project called Apollo.

Thank you

**Comment by ClassicOldSong** [comment]
You need to download psexec and change the start script a bit. Open the script with a text editor and there're instructions for them.

**Comment by motsch94** [comment]
Thank you for your reply.
I have also just downloaded the psexec and put them to C:/Tools/PSTools/
The script i put to C:/Tools/sunshine-tools/

And I also edit the paths in the Script.
I did all this just before I opened the thread here.
But it didnt work.
Firstly I would start the second apollo instance manually. But I dont know how.
Where do I have to put "sunshine.exe path\to\sunshine_2.conf"

Thank you!

Is there a possibility to donate for the Project?

**Comment by ClassicOldSong** [comment]
Execute it in an elevated CMD/PowerShell. But you would meet the problem where you can't click UAC dialog and enter login password by launching it this way. Use the shortcut method below is better.

**Comment by motsch94** [comment]
Thank you for the reply.
But in the shortcut properties of the second Apollo instance, where must I type the path of the sunshine_2.conf
the path is C:/ProgramFiles/Apollo/config

How must the shortcut look like?
Target
Start in
Comment

Thank you to use your time for my problem.
I would try to fix it at the evening

**Comment by ClassicOldSong** [comment]
You need to create a shortcut to the `start-apollo.ps1`, not modifying the original shortcut.

**Comment by motsch94** [comment]
Ok, I will try again, but also from this guide i tryed yesterday

**Comment by motsch94** [comment]
So now I was able to run the 2 Apollo instances.
My error was, that the Powershell/CMD Script was´t running as Admin.
When I added the additional line in the script it worked.

But now I can not connect with Moonlight to the Virtual Monitor.
I would connect to my Virtual Machine (Windows 10), hosted on a Unraid Server   who is in another room.
I am sitting in my room and try to connect with my Wyse 5070 running Windows 10.
On the server is NOT connected a physically Monitor. Do I have to connect one?

**Comment by motsch94** [comment]
![Unbenannt](https://github.com/user-attachments/assets/b65190e5-758d-460a-aa6c-cd32861fd1e0)

I tried with Virtual Desktop

**Comment by ClassicOldSong** [comment]
You can enable headless mode and there's no need for a physically connected monitor.

**Comment by motsch94** [comment]
Headless mode is just activated for both instances.

**Comment by ClassicOldSong** [comment]
You need to post your host's log instead of client side error message.

**Comment by motsch94** [comment]
my config file looks like this:

![Screenshot_20241204_082852_com microsoft rdc androidx](https://github.com/user-attachments/assets/ccee44f5-eabc-4695-a140-62c9c05e60cf)

**Comment by ClassicOldSong** [comment]
You need to post the log from the troubleshooting page.

**Comment by motsch94** [comment]
[sunshine_1.log](https://github.com/user-attachments/files/18004211/sunshine_1.log)

**Comment by ClassicOldSong** [comment]
Do not remove information from the log. Run dxgi-info.exe and post the output here. If you're using PCIE passthrough with nVidia cards there might be problems with the driver. Nobody can help despite contacting nVidia to sersuade them allowing PCIE passthrough on consumer cards.

**Comment by ClassicOldSong** [comment]
Also logoff your RDP session and try again.

**Comment by motsch94** [comment]
![Screenshot_20241204_102640](https://github.com/user-attachments/assets/080654b3-aa9f-4851-b1f5-23f7f56da0db)
now I am connected vua RDP from Phone, because I am not at home.
Yesterday I connected via Moonlight (Virtual Desktop) when RDP was closed.
Tgen appeared the error that no monitor is connected.

I installed Anydesk on the Thin Client, also on the VM. When Anydesk was connected, I was also able to connect via Moonlight-Apollo.

Yes a Nvidia GPU is passtrough from Unraid to the VM.

**Comment by ClassicOldSong** [comment]
You may force use CPU encoder then. Usage like this isn't expected and is not supported.

> Yesterday I connected via Moonlight (Virtual Desktop) when RDP was closed.

You need to make sure you have logged out of your RDP session, simpling disconnecting doesn't log you out.
