### ISSUE TITLE
Virtual display stays connected and active

### ISSUE THREAD

**Issue by CommonMugger** [ClassicOldSong/Apollo#132]
Maybe I installed/setup Apollo and the virtual display incorrectly, but when I installed the virtual display, it showed up as monitor 3 (I have 2 physical monitors), and stays active. 

When I start a stream, it uses the virtual display correctly and everything, but when I exit the stream via Moonlight, the virtual display stays active, as an extended monitor.

I was under the impression that it should be activated once a stream starts, then disconnected once a stream ends. Is that not the case?

On Windows Version 23H2.

**Comment by ClassicOldSong** [comment]
You don't need to install the virtual display dirver separetely. Apollo has one built-in, and it's different from the one form MTT.

The virtual display will remove itself when you terminate the app, it'll stay connected if you only disconnect but not end the stream.

**Comment by CommonMugger** [comment]
Hot damn. Thanks Classic for the quick reply, I appreciate your work!
