### ISSUE TITLE
Headless Mode not sending video 

### ISSUE THREAD

**Issue by JohnnyBlocks** [ClassicOldSong/Apollo#133]
Hello... Love your software.  I had things working perfectly, but the session did not end when the game closed.   Reading Issue #132 I was worried I might have had some other display adapter installed from tring to get sunshine to work initially.

To see if this was apollo's virtual display or another, I disabled SudoMaker Virtual Display Adapter in the Device Manager.   This caused things not to work, so I enabled it.  Now stream is black in headless mode, but audio is working.

Persists across both my client devices.

I reinstalled apollo but still back stream in headless mode.

Uninstall SudoMaker Virtual Display Adapter, Rebooted. 

Reinstalled Apollo, still no video in Headless mode.

Disable Headless mode allows the stream video to work.

Error log shows Error: DuplicateOutput() test failed [0x887A0004]

Sorry I've made a mess of it.   

[2024-12-04 20:58:45.708]: Error: [av1_qsv @ 0000022c1934c040] Current codec type is unsupported
[2024-12-04 20:58:45.708]: Error: [av1_qsv @ 0000022c1934c040] some encoding parameters are not supported by the QSV runtime. Please double check the input parameters.
[2024-12-04 20:58:45.709]: Error: Could not open codec [av1_qsv]: Function not implemented
[2024-12-04 20:58:46.909]: Error: DuplicateOutput() test failed [0x887A0004]

**Comment by ClassicOldSong** [comment]
Have you set Adapter Name in your config? If you have remove it, reboot and try again.

**Comment by JohnnyBlocks** [comment]
No, config is blank... It was automatically working so I didnt specify anything in those.  

I have 2 monitors and when active, I see the third created in my display properties.   It's just not connecting to it for video stream.

I'm guessing the driver is working because I can stream the standard desktop, but the headless monitor creates the resolution of my device so I get more frames (800 SteamDeck vs 2k normal display) when it streams.

**Comment by ClassicOldSong** [comment]
Please post your computer configuration and the output of dxgi-info.exe

**Comment by JohnnyBlocks** [comment]
Win 11 Pro - 23H2 -  i7-14700   2.10 GHz  
(Using phone as client with this output.  Mouse input works from phone, sound works, no video)


====== ADAPTER =====
Device Name      : NVIDIA TITAN Xp
Device Vendor ID : 0x000010DE
Device Device ID : 0x00001B02
Device Video Mem : 12125 MiB
Device Sys Mem   : 0 MiB
Share Sys Mem    : 16227 MiB

    ====== OUTPUT ======
    Output Name       : \\.\DISPLAY9
    AttachedToDesktop : yes
    Resolution        : 1280x720

    Output Name       : \\.\DISPLAY1
    AttachedToDesktop : yes
    Resolution        : 2560x1440

    Output Name       : \\.\DISPLAY2
    AttachedToDesktop : yes
    Resolution        : 1440x2560

====== ADAPTER =====
Device Name      : Intel(R) UHD Graphics 770
Device Vendor ID : 0x00008086
Device Device ID : 0x0000A780
Device Video Mem : 128 MiB
Device Sys Mem   : 0 MiB
Share Sys Mem    : 16227 MiB

    ====== OUTPUT ======
====== ADAPTER =====
Device Name      : NVIDIA TITAN Xp
Device Vendor ID : 0x000010DE
Device Device ID : 0x00001B02
Device Video Mem : 12125 MiB
Device Sys Mem   : 0 MiB
Share Sys Mem    : 16227 MiB

    ====== OUTPUT ======
====== ADAPTER =====
Device Name      : Microsoft Basic Render Driver
Device Vendor ID : 0x00001414
Device Device ID : 0x0000008C
Device Video Mem : 0 MiB
Device Sys Mem   : 0 MiB
Share Sys Mem    : 16227 MiB

    ====== OUTPUT ======
Press any key to continue . . .

**Comment by ClassicOldSong** [comment]
Your computer cannot handle AV1 encoding but somehow it's trying to use AV1 on your iGPU. To force use dGPU you need to fill the Adapter Name section with `NVIDIA TITAN Xp`.

**Comment by JohnnyBlocks** [comment]
Okay... I will do that.

I specified \\.\DISPLAY9 and that allowed it to work just like it was before I fowled it up, with the default non-specified config.

But I am guessing that DISPLAY9 is dynamic and might not always be Display9, so by specifying adaptor it will always use the dGPU no matter what the display identifier is?

**Comment by ClassicOldSong** [comment]
Leave Output Name blank, the display ID will change each time.

**Comment by JohnnyBlocks** [comment]
That worked.  It's all working again.  Thank you.  I do see this in the logs:

[2024-12-05 06:44:42.689]: Error: NvEnc: encoding format is not supported by the gpu


While I have you (and I can make a new ticket if you'd like) is there a way to have it end the session when the application stops?   

For example, I start GAME_A and stream it to my phone or steamdeck.   Finish my session and close game.   It then goes to the windows desktop.  

Is it possible to configure to end the session instead of returning to desktop?

**Comment by JohnnyBlocks** [comment]
Gotcha... Thank you for all of your help.  

I appreciate your time very much and your software really helps me.  

Thank you.  Deep bows of gratitude.  🙏🏻

**Comment by ClassicOldSong** [comment]
You're welcome!
