### ISSUE TITLE
Moonlight direct launch virtual desktop

### ISSUE THREAD

**Issue by wheeliemonster** [ClassicOldSong/Apollo#134]
Hi. Firstly, thank you for a great piece of software!

Using the Moonlight client (Windows) I can directly launch a client session using the format:

moonlight.exe stream pc-name.lan app-name

This supports directly opening a desktop session using the app-name of "desktop"
The virtual desktop option in Apollo doesn't appear to be listed in the application config, so is there a way to launch a virtual desktop session directly in this way, please?

Thank you

**Comment by ClassicOldSong** [comment]
You can configure the app to always launch in virtual display. Look closer into the app configuration you'll find more.
