### ISSUE TITLE
Nvidia DSR

### ISSUE THREAD

**Issue by woiza** [ClassicOldSong/Apollo#135]
Hi,

do you know how I can use Nvidia DSR and DL-DSR factors/resolutions with the virtual screen? Looks like they are only available when I use my main monitor for streaming.

**Comment by ClassicOldSong** [comment]
Nvidia's own settings can only tweak physically connected displays. I haven't tried but maybe you can use Lossless Scaling on the virtual display.

**Comment by woiza** [comment]
Thanks, I will try that

**Comment by woiza** [comment]
@ClassicOldSong 
Can I configure Apollo in such a way that moonlight clients can choose between the virtual screen and my main monitor? Or should I install Sunshine next to Apollo using different ports?

**Comment by ClassicOldSong** [comment]
When not using Headless mode, apps without "Always use Virtual Display" will launch on your physical display. Or you can use Artemis, long press on the app icon can select launch on virtual display or not.
