### ISSUE TITLE
Unable to use AV1 Codec for Streaming

### ISSUE THREAD

**Issue by slychoober1** [ClassicOldSong/Apollo#137]
Hi, I'm facing an issue when attempting to use the AV1 Video Codec w/Hardware Decoding despite my GPU supporting AV1. 

I get an error message that says "This PC's GPU lacks support for decoding your chosen codec."

Here is my setup:
Host GPU: RTX 4070 Ti Super

Client Device: Steam Deck
Apollo Version 0.2.6-alpha.1
Moonlight 6.1.0 

Not sure to where to begin troubleshooting, any ideas would be greatly appreciated!

**Comment by ClassicOldSong** [comment]
Does your PC have an iGPU? If so, specify the Adapter Name in Audio/Video tab to your dGPU and enable headless mode.

**Comment by slychoober1** [comment]
I do not have an iGPU, using a 13600KF!

**Comment by ClassicOldSong** [comment]
And as I've written in the latest release, AV1 on nvidia cards is not recommended right now as it'll lag in some cases. Use HEVC should cover most use cases unless you want to stream in bandwidth limited scenarios.

**Comment by ClassicOldSong** [comment]
Oh, it's saying your client cannot decode AV1. What's your client?

**Comment by slychoober1** [comment]
I did see the release notes, just looking to understand what's preventing this from working!

My client is the Steam Deck and the Host has an RTX 4070 Ti Super

**Comment by ClassicOldSong** [comment]
Found this: https://github.com/moonlight-stream/moonlight-qt/issues/1460

**Comment by slychoober1** [comment]
I believe I'm using flatpak but let me confirm and report back, thanks for sharing that issue.

**Comment by slychoober1** [comment]
@ClassicOldSong All fixed, I'll continue to use HEVC per your recommendation but the troubleshooter in me wanted to get to the bottom of this.

**Comment by ClassicOldSong** [comment]
Maybe a driver update would solve this problem but it seems to be the encoder took too long to find differences between frames and failed - encoding delay increases and bandwidth uage shoots up, while AMD cards don't suffer from this problem and stays cool. I don't have dedicated Intel cards but integrated ones doesn't seem suffer from this issue either.

Client will report false decoding delay when this happens. That's another problem though...
