### ISSUE TITLE
Black Screen on starting stream

### ISSUE THREAD

**Issue by Rumik** [ClassicOldSong/Apollo#14]
Hi there,

Twice today and once yesterday I have tried to stream a game from Apollo and all I've gotten is a black screen with audio in the background. Killing the process and restarting fixes it.

Streaming via Moonlight-qt on Steam Deck.

Thanks

**Comment by ClassicOldSong** [comment]
Are you streaming with virtual display or just ordinary desktop mirroring? And what's your computer configuration?

**Comment by Rumik** [comment]
I am using a virtual display. There may have been a conflict with MoonDeck's "pass resolution to host" setting, which I have now disabled, and haven't seen the black screen again. I'll leave this open for a little longer just in case, as I intend to test this thoroughly over the next week.

**Comment by Rumik** [comment]
Scratch that, it just happened again. Seems to be related to the virtual display.

System: Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz   3.70 GHz, 64GB RAM, GeForce RTX 3070.

**Comment by ClassicOldSong** [comment]
Does reconnecting (not killing the current process) help? Can you try when the black screen happens, exit the stream from your deck and reconnect with another client to see if it's still black?

Also please make sure you're on the latest graphics card driver.

**Comment by ClassicOldSong** [comment]
Maybe you can try again with their nightly build. Apollo includes their nightly changes.

By saying encoding, I mean if you're using HEVC/H264 or AV1.

**Comment by Rumik** [comment]
I've narrowed this down a little bit... this only happens when my physical displays are turned off. If they're on, then the stream connects fine, although the game window isn't on the right display. When they are turned off, the black screen issue happens. Disconnecting the session in the client restores the resolution just fine when the physical displays are on. When they are off and the black screen happens, disconnecting the client does not restore the previous resolution.

**Comment by ClassicOldSong** [comment]
Hmmm, is the virtual display still connected when the black screen issue happens? Could you check the driver status showed both on audio/video tab and in device manager when the black screen happens?

By the term "turn off", did you turn the monitor off physically or just in Windows Setting? It seems you have 2 physical monitors, which one are you turning off?

Would you enable Headless Mode in audio/video settings and try again?

You can use Win+P and select Extended to make both the built in display and virtual monitor work.

Sorry for so much questions but I need more information to locate the source of the issue.

**Comment by ClassicOldSong** [comment]
Does this still happen now? If it still happens, can you confirm that this happens on a clean installation of Window?

As far as I know, this is the only case with this issue, it's likely that it's related to your setup. There's another user group not on GitHub, but no one reported similar issues.

**Comment by Rumik** [comment]
I've actually just got a new PC so I've been setting it up and testing it. So far I have not seen this issue, but I haven't had a lot of opportunities to try. It's probably fine now :)
