### ISSUE TITLE
huge bandwidth spike when streaming 

### ISSUE THREAD

**Issue by AmplificPanda** [ClassicOldSong/Apollo#140]
Hi there, 
i am the guy whos been having the packet loss every 20 minutes over WiFi. 

Today I plugged in the Ethernet cable and discovered that every 20 minutes, the bandwidth is spiking to 6000 MB/S... which can't be right since my network can only support 1 Gigabit. 

I have no idea what could be causing the bandwidth to spike this high during streaming... I am guessing this is why my U6 Lite had been dropping packets, the bandwidth spike was simply way too high for it. 

I have set the bitrate to 70mbps, and I can see the bandwidth reflected as 9.44M/S while streaming. 

The host PC does not have any other applications running other than Playnite & whatever game launcher is active when playing a game. background apps and downloading are turned off. 

Weirdly though this issue may have been happening with Steam Link too, so it may not be a moonlight/Apollo issue. However, I'd still appreciate some advice on how to go about determining what is causing the bandwidth spike.

**Comment by ClassicOldSong** [comment]
Moonlight's bandwidth calculation is flawed(but should not be this much), but if it's also happening on Steam Link, and it happens both when wired and wireless, you might need to check your client...

Or you can run Wireshark and try to capture the packages when it shoots up to 6000M/s, to see what's going on...

**Comment by AmplificPanda** [comment]
Is the bandwidth figure relating to the clients bandwidth of the bandwidth of the network itself from the PC to the client? 

If its the bandwidth from the client only, it only puzzles me through multiple factory resets of the Nvidia Shield Pro 2019, the problem persists.

**Comment by ClassicOldSong** [comment]
It should be client only.

Can be multiple factors, and some are really hard to believe (e.g. Intel 13-14Gen CPU issue, XBOX red ring of death, this can also happen to mobile CPUs/router cpus and their memory/nics), but usually it's software issues. To be sure you can check the bandwidth usage on your host first and cross compare between your client's reports.

**Comment by AmplificPanda** [comment]
Heyo, how do I check host bandwidth? 

I restarted the shield and the spikes haven't returned yet. 

Hence I think this might be only an issue with WiFi via a U6 Lite/Any Ubiquiti access point.

**Comment by ClassicOldSong** [comment]
For ease of use GlassWire should be enough, for professionals use WireShark.

**Comment by AmplificPanda** [comment]
Ok this may actually also be because of a USW 8 Lite Switch...It may not be fast enough to handle the micro bursts that Sunshine/Apollo can emit. I see TX drops of 923 from the switch port connected to the router.

**Comment by ClassicOldSong** [comment]
This still shouldn't happen as I have some very cheap switches that can handle high bandwidth without problems.

Doesn't seem happen often and is likely a user specie issue, closing this now. Feel free to open again if you find out there's more relationship with Apollo.
