### ISSUE TITLE
Virtual display not set as primary

### ISSUE THREAD

**Issue by framosk** [ClassicOldSong/Apollo#145]
The virtual view was created, but for some reason it cannot be set as primary, can you please check this problem?
Yes, I am using Windows 11 24H2 😊
Logs attached
[sunshine_issue.log](https://github.com/user-attachments/files/18103227/sunshine_issue.log)

```
[2024-12-11 22:39:10.884]: Info: Virtual Display created at \\.\DISPLAY8
[2024-12-11 22:39:11.075]: Info: Setting display \\.\DISPLAY8 primary
[2024-12-11 22:39:11.173]: Info: Setting display \\.\DISPLAY8 primary failed! Are you using Windows 11 24H2?
```

Can you check it, please?

Thank you in advance😊

**Comment by ClassicOldSong** [comment]
You can only set it manually in Windows settings if you're using 24H2. That's why the log is there.

**Comment by fcakyon** [comment]
How to manually set that in WIndows settings @ClassicOldSong @framosk ? I couldn't find any documentation about that 😅

**Comment by ClassicOldSong** [comment]
Here I found a video tutorial for that https://youtu.be/qbGCSQwhOh4

Remember that you need to do this while you're streaming, the virtual display only exists when you have started an app. After the change, terminate the app and start streaming again.
