### ISSUE TITLE
Steam Big Picture starting on physical screen instead of virtual display

### ISSUE THREAD

**Issue by arafatm** [ClassicOldSong/Apollo#149]
Hello, I apologize if I'm missing something obvious.

Before I go on to my query I just want to point out that the docs link you provide in the readme no longer works. https://sushinestream.readthedocs.io/ returns a 404.

As to my query, when I launch steam big picture with moonlight on my steamdeck, the virtual display is created correctly. However, steam big picture gets launched on the physical display. How can i get big picture to launch on the newly created virtual display. Afaict the virtual display has the right resolution and is created as primary. If I hit alt-tab or the win key i see it on the streamed virtual display.

Here are my settings.

This one is from the A/V config
![image](https://github.com/user-attachments/assets/2fe04c38-1413-4396-8879-9b584b22a949)

This one is from the steam big picture config
![image](https://github.com/user-attachments/assets/49778bfa-f2d4-463c-b010-64312f8c8220)

**Comment by ClassicOldSong** [comment]
The enforce option doesn't work on Windows 11 24H2, it's written as a notice in the release notes.

If you manually set the virtual display to primary once and steam big picture still doesn't launch on the new display, you need to check if you have set which display it shows on in Steam settings.

**Comment by arafatm** [comment]
Thank you. I'll try that.
