### ISSUE TITLE
where to find login details?

### ISSUE THREAD

**Issue by Deph1** [ClassicOldSong/Apollo#159]
Hello, on windows 11 I have installed apollo but when it goes to local host, i'm prompted for a user and pass that I do not have and there is no mention in the github and the docs url only provides a 404. 

Thanks

**Comment by ClassicOldSong** [comment]
The first time you open the page it prompts you to set your username and password.

**Comment by ClassicOldSong** [comment]
Any updates? Is this problem solved?

**Comment by ClassicOldSong** [comment]
Close it for now, seems to be an user specific issue.
