### ISSUE TITLE
Virtual Display does not restore host machine's native resolution

### ISSUE THREAD

**Issue by Rumik** [ClassicOldSong/Apollo#16]
Hi there.

I've been playing around with streaming, switching back and forth between the Deck's internal display and an external 4k screen. What I've noticed is that Apollo's virtual display will switch to the correct resolution the first time, but on disconnecting the stream the resolution does not get restored. I am quitting the stream using Moonlight's Start+Select+LB+RB shortcut.

Thanks.

**Comment by ClassicOldSong** [comment]
I don't have a deck so I'm not sure what that button combination means. I suppose it's only disconnecting the stream but not actually quitting the app. The virtual display should automatically disconnect only when the app you're streaming quits.

**Comment by ClassicOldSong** [comment]
If you want to change the resolution of your virtual monitor you have to quit the app, make sure Moonlight reads the new resolution you desired and start streaming again. The resolution won't change without exiting the app.

**Comment by Rumik** [comment]
I just had another test. the virtual display resolution was changed to 1280x800 when the game started. I killed the game process and the virtual display did not return to its previous resolution. What exactly needs to happen for the resolution to change back?

FYI this is running a Steam shortcut via the command steam://rungameid/1593500

**Comment by ClassicOldSong** [comment]
The virtual display should be disconnected, not restored to a certain resolution. Are you still using something else for virtual display? Could you remove them and try again?

**Comment by tkazbekov2** [comment]
@ClassicOldSong  The Start+Select+LB+RB combination is a gamepad shortcut that equals SHIFT+CTRL+ALT+Q on windows, triggers exactly the same way I thought.

@Rumik could we start from the beginning? You switch between a 4k monitor and the Deck's internal display.
Now, let's isolate the issue - when does the virtual display get the correct resolution set? When it's connected to the external monitor or when using the internal one? Maybe let's talk about just the internal display for now because I am having an issue trying to process the report.

Sorry for being so obnoxious, I won't be able to contribute anything meaningful anytime soon, so I thought maybe I could help out with getting reports more streamlined

**Comment by ClassicOldSong** [comment]
So that means by pressing the button combination it's only disconnecting the stream, but not quitting the app. In this case the virtual display indeed is not removed.

**Comment by Rumik** [comment]
@tkazbekov2 the virtual display does correctly set the resolution based on whether I'm using the Deck's internal display or a connected 4k tv. I think my expectations for disconnecting the virtual monitor was when the stream is ended, rather than when closing the app. I would very much appreciate it if the virtual monitor could be disconnected when killing the stream or closing the app - both would solve all my issues :D

**Comment by ClassicOldSong** [comment]
I have updated the README, you can just treat your device as a physical monitor, which means it can't change resolution without reconnecting, or you just go to Windows settings to adjust its current resolution.

I understand now that you want the virtual display to be disconnected when you're exiting the stream but not stopping the app, and re-attach with the resolution matched from another client, is it correct?

**Comment by Rumik** [comment]
That sounds about right, yes :)

**Comment by ClassicOldSong** [comment]
After some careful consideration I don't think it's a good idea to go with this behavior.

Firstly, when restoring, the app you're currently running might not go back to the virtual display.

Secondly, when there're multiple connections to view a same stream, there might be more confusions between how viewers get their view and whether to disconnect the virtual display when a client disconnects.

If you want this behavior, you can start your app in detached commands and exit the app each time you disconnect as a workaround.
