### ISSUE TITLE
Black screen after installing

### ISSUE THREAD

**Issue by cctry** [ClassicOldSong/Apollo#162]
Hi,

My system got frozen after the installation and the screen is black even after the reboot. I resolved it by uninstalling Apollo in safet mode, but the system is unstable that the taskbar becomes not responding frequently. 

I am not sure if there is any component left. Could you please provide an instruction for a clean uninstallation?

I am using Win10 22H2

**Comment by ClassicOldSong** [comment]
Have you installed any other virtual display drivers? Apollo's driver won't make you black screen after reboot, as it doesn't create persistent virtual display like the other one. You don't need to manually install any virtual display driver with Apollo, it's built-in with the installer.

Apollo shouldn't have any unremovable component that could cause freezes, you should check if it's something else causing the problem.

**Comment by cctry** [comment]
> Have you installed any other virtual display drivers?

I don't think so. How do I check it?

**Comment by ClassicOldSong** [comment]
Go to device manager, under Display Adapters see if there's something else.

Windows 10 is not guaranteed to work as I don't have a machine with 22H2 installed. But 22H2 is reported working from other users.

**Comment by cctry** [comment]
Thanks for explaining this.
I found a Citrix IDA under the adapters, but I don't know when it was installed.

Also, my system problem is due to the corrected gdiplus.dll. There might be some magic that happened after the installation and ruined everything. 

Anyway, thanks for your prompt response.
