### ISSUE TITLE
Black Screen on Connect

### ISSUE THREAD

**Issue by elmerg999** [ClassicOldSong/Apollo#163]
HI. Using a normal Moonlight connection from modded Switch OLED, I'm receiving only a black screen when connecting to the Virtual Display. Computer is set up to extend, but nothing shows up on the VD unless I make it 'mirror'. If I click other options than the Virtual Display, it just opens those things on my normal monitors.

**Comment by ClassicOldSong** [comment]
If you connect when your computer is locked and the virtual display isn't primary, it'll show a black screen by Windows. You can disable your physical monitor if it's not needed while streaming l.

**Comment by elmerg999** [comment]
In order to test, I connected while the computer was unlocked. It seemed to create the virtual display just fine, as it was in my Display options when I opened them. Does the virtual display need to be the 'default' always? I'd prefer it when screen is on I could still stream and play, but mostly wanting an option to do streaming w/o my screens having to be on.

**Comment by elmerg999** [comment]
More updates.
- Setting Headless Mode made the black screen go away, and I get the extended desktop.
- With computer unlocked, Steam Big Picture opened in the virtual display. Playnite did not.
- With computer locked, trying Big Picture or Playnite just gets a stream failed to start. But the virtual display still starts, as I have to go to Desktop from the remote to unlock my computer, and the item I tried to start did start up. 
- When exiting via terminate app, the app terminated on my device, but Big Picture did not close down on the computer itself. 
- I'm using the latest version of Moonlight-Switch.

Any thoughts on the locked computer issue? One step forward, one step back, but progress.

**Comment by ClassicOldSong** [comment]
> * Playnite did not.

Playnite has its own config for displaying on which monitor. You need to change it to start on primary monitor.

> * When exiting via terminate app, the app terminated on my device, but Big Picture did not close down on the computer itself.

If Steam starts before the stream starts, Big Picture won't close as it's not managed by Apollo.

> * Setting Headless Mode made the black screen go away, and I get the extended desktop.

So it seems to be your computer has two GPUs and your primary display is connected to the other GPU other than the streaming GPU which is auto selected by the driver.

> Any thoughts on the locked computer issue?

Nope, Big Picture starts fine when locked on my computer but I haven't tried with Playnite. There's an auto unlock script in the [WiKi](https://github.com/ClassicOldSong/Apollo/wiki/Auto-lock-unlock-Windows) but it's not that reliable.

**Comment by elmerg999** [comment]
> Playnite has its own config for displaying on which monitor. You need to change it to start on primary monitor.

Thanks for all the help. I looked but must have overlooked it. I figured out the right syntax to add my emulators to Steam directly, so that seems to be sorted without Playnite anyway.

> If Steam starts before the stream starts, Big Picture won't close as it's not managed by Apollo.

So sounds like I just need to set steam to close fully when finished rather than just minimize, and not start with my computer. Okay. 
 
> So it seems to be your computer has two GPUs and your primary display is connected to the other GPU other than the streaming GPU which is auto selected by the driver.

I have the RTX above and a basic Intel GPU. I didn't think listing them both would be needed. I'll have to look to see what options I need to change here, if any. 

> Nope, Big Picture starts fine when locked on my computer but I haven't tried with Playnite. There's an auto unlock script in the [WiKi](https://github.com/ClassicOldSong/Apollo/wiki/Auto-lock-unlock-Windows) but it's not that reliable.

Wonder if it's related to the GPU thing. Big Picture starts but I get the stream can't start error. More testing to be done. Thank yiou for all your help, BTW, and have a great holiday if you celebrate it.

**Comment by ClassicOldSong** [comment]
If you don't need your iGPU you can just disable it in the bios. If you don't want to disable it you can set the `Adapter Name` to your dGPU, then the driver will always use your dGPU for virtual display and streaming. Note that if your primary monitor connects to your motherboard's video port, it'll fail to stream from your primary monitor when you set `Adapter Name` to dGPU.

**Comment by xDaveN** [comment]
> Playnite has its own config for displaying on which monitor. You need to change it to start on primary monitor.

For me the virtual display never becomes the primary monitor in the first place. Did I miss something during setup?
I can just pick the virtual display in Playnite and it will launch there next time, so it's kind of a non issue, but it got me wondering, should the vritual display be the main monitor?

**Comment by ClassicOldSong** [comment]
Try the latest version and go to `Audio/Video` tab, in `Advanced display device options` section, set `Device configuration` to `Activate the display automatically and make it a primary display`. Also make sure the app has set preferred display to None or Auto.

**Comment by xDaveN** [comment]
Cheers for the reply. I must've missed that.
I added the setting, but somehow this bricked my SudoVDA, lol.
Didn't have an issue with this before, but it just switched to "SudoVDA Driver status: Uninitialized" despite only changing the setting you've mentioned. Funky.

**Comment by ClassicOldSong** [comment]
A reboot might be all you need. The driver is upgraded/reinstalled every time when you upgrade Apollo, maybe this time Windows got stuck somewhere.

**Comment by xDaveN** [comment]
You're right. I did my Sunshine uninstallation and Apollo install within a single boot and kept running into issues with SudoVDA. Classic, but seems to be resolved now. Thanks for the quick replies!
