### ISSUE TITLE
HDR not working with Steam Deck OLED

### ISSUE THREAD

**Issue by DaLuke95** [ClassicOldSong/Apollo#173]
Hi,

Great fork, but can we get HDR working?

Problem statement:

Everything works, except HDR

Host: 
Windows 10
5800x3d 
RTX 4070 TI SUPER

Client
Steam Deck Oled 
Moonlight
HDR enabled in settings

HDR works on normal Host + LG C9 but not on client. 
Doesn't even come up on Virtual Display when trying to enable it on Host

Help is much appreciated!

**Comment by ClassicOldSong** [comment]
Windows 10 does not support HDR with virtual display. You need Windows 11.

**Comment by DaLuke95** [comment]
Damn. When I upgrade to W11 should I uninstall Apollo before the upgrade and it'll just work or?

**Comment by ClassicOldSong** [comment]
It should just work on 24H2, on 23H2 there're cases HDR doesn't work but that's rare.

**Comment by DaLuke95** [comment]
Ah I see! I just really wanted to avoid W11 as long as possible to be honest. I have some old Soundblaster installed and went through a lot to get it working. Don't want W11 to ruin that atm.

And since you're not recommending HDR so much I think I'll hold out on it for now.
All the other solutions with HDR on W10 are just to annoying for me anyway.


________________________________

**Comment by ClassicOldSong** [comment]
Also check these out if you're interested in vintage sound cards:

https://www.youtube.com/watch?v=WsSY0C8ivOA

https://www.youtube.com/watch?v=dg33QLkHAu4

It's made by us :)

**Comment by DaLuke95** [comment]
No waaay dude! I only have an external one (cuz I didn't have room for an internal one) called Omni Surround. I'm just playing on my TV and via hdmi the delay was horrendous (my avr doesn't support earc).
So yeah I'm very scared. 

It's crazy that you're also producing these though!
Is there any way I can donate a bit for Apollo?

**Comment by DaLuke95** [comment]
Do you think the upgrade to W11 is worth it overall?

**Comment by ClassicOldSong** [comment]
> Is there any way I can donate a bit for Apollo?

See if anything you like: https://su.mk/store

It's totally fine you don't find anything useful to you

> Do you think the upgrade to W11 is worth it overall?

Mostly it's a big experience upgrade from Win10. But those copilot things are getting along with Windows11 lol

**Comment by DaLuke95** [comment]
Not right now, gotta get more invested in these kind of things I guess.

Btw, bit the bullet to the upgrade now. You were right.
HDR worked out of the box (after turning it on ofc)
Aaand, Soundblaster omni still working yay!

Again, I really think Apollo is great man. Especially with the Steam Deck OLED and such. If theres any way I can contribute, let me know!

**Comment by ClassicOldSong** [comment]
You're welcome!

If you really want to contribute, use this Patreon for now: https://www.patreon.com/c/classicoldsong , It's meant for my general development on open source.

**Comment by DaLuke95** [comment]
Done! Put in kinda like a one time donation / one month for 10 bucks. Cheers again mate!
________________________________

**Comment by ClassicOldSong** [comment]
Thank you very much! And Happy New Year!
