### ISSUE TITLE
bug about cover

### ISSUE THREAD

**Issue by LYYAradn** [ClassicOldSong/Apollo#18]
i dont find anyone about png 
![GFFV1YIL8KEN(T4PD`LDWN9](https://github.com/user-attachments/assets/037b06cb-05dd-40bc-a870-98da0beaf297)
![U3H2 308AMG(DUM18VEDZHH](https://github.com/user-attachments/assets/7b904e50-4c40-4b52-8e79-0ff60b655d1d)

**Comment by LYYAradn** [comment]
it also happen on desktop and steam

**Comment by ClassicOldSong** [comment]
That find cover tool seldom works. I haven't touched the code from that part, it should work the same as og Sunshine.

Enter the path to your image manually should work.

**Comment by Rumik** [comment]
I have this problem too. Works 99% of the time on Sunshine, not at all on Apollo :(

**Comment by LYYAradn** [comment]
> That find cover tool seldom works. I haven't touched the code from that part, it should work the same as og Sunshine.
> 
> Enter the path to your image manually should work.

this method is the right one

**Comment by ClassicOldSong** [comment]
The searching works for me. It's placed in a very ambiguous position so you might get confused with it. The confusion will be fixed in the next release.

**Comment by ReenigneArcher** [comment]
Just FYI, in Sunshine, this feature searches our https://github.com/LizardByte/db repo. It uses the application/game name to perform the search, and the name should be the same as used on igdb (https://www.igdb.com/).

It was never intended to search local directories.

**Comment by ClassicOldSong** [comment]
@ReenigneArcher this is easily fixable with a simple UI tweak to remove the confusion. Just check the commit that closes this issue.
