### ISSUE TITLE
Some problems about Headless Mode

### ISSUE THREAD

**Issue by ZhaoZelin2000** [ClassicOldSong/Apollo#20]
![image](https://github.com/user-attachments/assets/3977e774-3aa8-4bb7-a7fc-9863a019ead8)
Some software interfaces that I have already opened are displayed on other screens, making it difficult for me to transfer them to the virtual screen. In addition, can we automatically determine the local screen layout and enable the corresponding screen layout on the client side, just like Microsoft's RDP，“Use all my monitors for remote sessions”
![image](https://github.com/user-attachments/assets/2c20ba48-d2d1-44b6-b3d3-eb734d131dee)

**Comment by ClassicOldSong** [comment]
You can use Win+Shift+Left/Right to move the active window.

**Comment by ClassicOldSong** [comment]
If you're using the virtual display remotely, it's recommended to disable your built-in display when streaming. Just disable the physical monitors you can't access with Windows settings or Windows+P then select Display only on Monitor 2.

**Comment by ZhaoZelin2000** [comment]
> If you're using the virtual display remotely, it's recommended to disable your built-in display when streaming. Just disable the physical monitors you can't access with Windows settings or Windows+P then select Display only on Monitor 2.

I hope apollo can automatically disable the physical monitors when I use the headless model or virtual screen, and after I have disconnected the streaming, the physical monitors are back to normal. 
When I use pc, it is easy to set the screen layout.however, it is very difficult to set the screen layout when I use phone.

**Comment by ClassicOldSong** [comment]
Actually you can. Just press Win+P and select secondary monitor only. The next time you stream the built in display will automatically turn off.
