### ISSUE TITLE
Stream begins and then stops

### ISSUE THREAD

**Issue by Dr-Suprane** [ClassicOldSong/Apollo#22]
When launching Helldivers 2 or Marvel's GotG the virtual display kicks in as expected, I see the desktop now on Steamdeck launching and then after a few seconds the virtual display appears to "turn off."  This then leads to my primary display turning back on ( I used the windows option to turn off my primary display as noted on a Reddit comment you made prior) and the game continues to load correctly just without the stream.

Looking at the log it appears to exit each time with a code of 1 or -1.  I also do notice that the log mentions that the display cannot be found.

[2024-08-31 10:41:16.375]: Info: App exited with code [1]
[2024-08-31 10:41:16.953]: Info: Process terminated
[2024-08-31 10:41:16.985]: Warning: Desired display [\\.\DISPLAY35] does not exist

Configurations changed from default are with the applications options for forcing the virtual display and make it primary.

My setup is i9-13, 4090, 32gb RAM.  display is a Neo G9 super UW

**Comment by ClassicOldSong** [comment]
Can you provide a screenshot of your config on the web UI for these games? It seems that you haven't got `Continue streaming if the application exits quickly` ticked.

**Comment by Dr-Suprane** [comment]
![image](https://github.com/user-attachments/assets/c6b611d5-8a7e-4281-bda3-1f89b1770ee1)

**Comment by ClassicOldSong** [comment]
Try changing the command into steamid

The one you can take reference from the default "Desktop" app

**Comment by ClassicOldSong** [comment]
How to get the `steam://` link:

1. Go to Steam, right click on the game in your library, select `Manage` on the popup menu, then `Create Desktop Shortcut`
2. Right click, choose `Properties` on the desktop shortcut just created, copy the URL of the shortcut

**Comment by Dr-Suprane** [comment]
This worked.  I ended up finding online the way to alter it with steam://launch etc etc.  

The Marvel game is actually from Epic Game Store, I personally don’t know if EGS uses a different launch like Steam does.  I will attempt using the desktop shortcut as opposed to linking the .exe to see if it does anything different.

I will also test this with EA launcher (Jedi Survivor), Xbox gamepass game also and a Ubisoft launcher game then report back.

**Comment by ClassicOldSong** [comment]
You can try [Playnite](https://playnite.link/) as a unified game manager and launcher.

**Comment by Dr-Suprane** [comment]
Can confirm.  Epic games and EA desktop require using the desktop link path for the command in Apollo.  I assume playnite might be easier for me to use and will likely use that from now on.

Not sure if this is something you want to address eventually.  I will close this as resolved.  Thanks for your help.

**Comment by ClassicOldSong** [comment]
You can try if the latest version resolves your issue with using exes directly.
