### ISSUE TITLE
Virtual Display HDR colours

### ISSUE THREAD

**Issue by Rumik** [ClassicOldSong/Apollo#23]
Hi there,

With HDR enabled on the virtual display, on first launch of the stream the colours are super intense. I have to go into display settings and disable/re-enable HDR to fix it, which is a little tricky to do in my tv hehe. Any ideas what the issue is?

HDR is also enabled in Steam Deck settings, fyi.

**Comment by ClassicOldSong** [comment]
Seems to be stream starting too fast after the display is added 
Will try to fix in the next update

**Comment by Rumik** [comment]
Glad you could reproduce it. Thanks, looking forward to that :)

**Comment by ClassicOldSong** [comment]
Can you try https://github.com/ClassicOldSong/Apollo/releases/tag/v0.1.2-alpha.1 to see if it solves the issue?

**Comment by ClassicOldSong** [comment]
Can you post the whole log here? Might 200ms of wait still too short for you but they work stably for me.

This is not easily fixable since it's actually Windows got the format wrong at start up, all I can do is workaround this behavior...

**Comment by j-scrizz** [comment]
Yes same issue here.

**Comment by ClassicOldSong** [comment]
Try this version again, if it's still not working please post a whole log from when Apollo starts to after you toggled the HDR switches.

https://github.com/ClassicOldSong/Apollo/releases/tag/v0.1.2-alpha.2

**Comment by Rumik** [comment]
Seems to be working now! Nice one!

**Comment by j-scrizz** [comment]
Still not working here, I will send you my logs, where do I find them?

**Comment by ClassicOldSong** [comment]
According to your log, it's working correctly. What's the actual symptom you're facing?

Make sure you have HDR enabled on your client and virtual display. You might see over saturated color for a short period (<1s) but it should auto correct later.

**Comment by j-scrizz** [comment]
Thanks guys, I think its actually got something to do with the client I am using. The moonlight client for xbox. I believe its not doing the "handshake" correctly. I see the logs are saying my HDR should be working fine, but my TV just doesnt kick into HDR mode. hopefully the moonlight xbox fork sorts it out.

**Comment by Rumik** [comment]
I've noticed the Xbox app has some strange ghosting effects going on- the stream is much lower quality overall compared to other clients.

**Comment by j-scrizz** [comment]
> I've noticed the Xbox app has some strange ghosting effects going on- the stream is much lower quality overall compared to other clients.

I believe it has something to do with bad blacks. Which having HDR seems to make it alot better. as with HDR it becomes 10 bit. Which greatly improves the quality in my experience. hopefully it gets sorted.

**Comment by ClassicOldSong** [comment]
I have issues with the xbox client as well. I don't do UWP developing so unfortunately I can't help now. Hope the xbox client will fix this issue in the future.

**Comment by epthewizard** [comment]
Is there a way to just disable HDR within Apollo? I don't want to have to turn off HDR on my machine before connecting and do not care whether it is present within the stream or not.

**Comment by ClassicOldSong** [comment]
> Is there a way to just disable HDR within Apollo? I don't want to have to turn off HDR on my machine before connecting and do not care whether it is present within the stream or not.

Go to Audio/Video tab, check `Follow Client's HDR config`. Make sure your client has HDR disabled.

**Comment by ClassicOldSong** [comment]
@Rumik @j-scrizz the latest release might have the Xbox issue fixed: under NVENC config, enable `Intra Refresh`.

**Comment by Rumik** [comment]
I'll give that a go!

**Comment by j-scrizz** [comment]
Damn, Na not working. Probably because I have an AMD GPU system, I still think its the xbox clients issue. he hasn't updated in 3 months.. so I hope he's still active!

**Comment by ClassicOldSong** [comment]
@j-scrizz yeah that option is for nvidia cards only. I didn't know that AMD cards also suffer from the same issue.

It is a Xbox client issue, but as it seems the actual cause burries more deeply that it can't be solved from the application itself, what left we can do is workaround from the host side.
