### ISSUE TITLE
Turn off main displays on stream.

### ISSUE THREAD

**Issue by j-scrizz** [ClassicOldSong/Apollo#26]
Any chance you could implement turning off the main screens on launch of apollo stream? Just so the virtual display is active.

**Comment by ClassicOldSong** [comment]
You can do this by turning off the main screen in Windows settings. The next time you stream it'll turn off automatically.

**Comment by ruifung** [comment]
Just ran into this, thought I'd leave a comment here for future users.

Using Nirsoft's MultiMonitorTool, I set up server commands for enabling and disabling my physically attached monitors like MultiMonitorTool.exe /disable <monitor id> and /enable <monitor id>

Also designated an application (Desktop in my case) with those as pre and post commands so it's automatically disabled when I connect to a specific application.

Also having MultiMonitorTool.exe /MoveWindow Primary All as a server command is handy too.

**Comment by Reszkettle** [comment]
Do you guys know if these displays are now automatically turned off with the combination of below settings?
- Deactivate other displays and activate only the specified display
- Headless Mode

**Comment by ClassicOldSong** [comment]
https://github.com/ClassicOldSong/Apollo/issues/469

**Comment by Xarishark** [comment]
#974

**Comment by craigcabrey** [comment]
> Just ran into this, thought I'd leave a comment here for future users.
> 
> Using Nirsoft's MultiMonitorTool, I set up server commands for enabling and disabling my physically attached monitors like MultiMonitorTool.exe /disable and /enable
> 
> Also designated an application (Desktop in my case) with those as pre and post commands so it's automatically disabled when I connect to a specific application.
> 
> Also having MultiMonitorTool.exe /MoveWindow Primary All as a server command is handy too.

How did you set this up? Nothing seems to happen when I have a prep command configured.

**Comment by ruifung** [comment]
Just for 

> > Just ran into this, thought I'd leave a comment here for future users.
> > Using Nirsoft's MultiMonitorTool, I set up server commands for enabling and disabling my physically attached monitors like MultiMonitorTool.exe /disable and /enable
> > Also designated an application (Desktop in my case) with those as pre and post commands so it's automatically disabled when I connect to a specific application.
> > Also having MultiMonitorTool.exe /MoveWindow Primary All as a server command is handy too.
> 
> How did you set this up? Nothing seems to happen when I have a prep command configured.

I no longer use MultiMonitorTool in prep commands since windows itself remembers which monitors I have enabled thanks to monitor identity being optionally per-app per-client now.

I still have it in server commands for manual triggering if I need it though.

I just have Something like
```C:\tools\path-tools\MultiMonitorTool.exe /disable <short monitor ID>```

Where short monitor ID is obtained from the UI of MultiMonitorTool.
Make sure you're actually running in Virtual Display mode!

**Comment by craigcabrey** [comment]
For future searchers: Apollo has built in functionality for this actually.

https://github.com/ClassicOldSong/Apollo/wiki/FAQ#i-want-to-turn-off-the-physical-monitor-when-streaming

**Comment by johnjack135** [comment]
Lol, the first comment in this thread is from the creator highlighting what that last link sent says and there's still a chain of people who didn't get it
