### ISSUE TITLE
Cannot get moondeckbuddy to work with Apollo

### ISSUE THREAD

**Issue by mysteriousHerb** [ClassicOldSong/Apollo#27]
Maybe very niche, but on steamdeck there is an app called moondeckbuddy that automatically spawns steam big picture and launch game with different appid for controller etc.
Is there a way to look into this? 

I already checked with moondeckbuddy developer the problem is likely on the sunshine side.

```
[2024-09-03 07:35:59.241]: Info: Desktop resolution [3440x1440]
[2024-09-03 07:35:59.241]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024-09-03 07:35:59.241]: Info: Display refresh rate [143.923Hz]
[2024-09-03 07:35:59.241]: Info: Requested frame rate [60fps]
[2024-09-03 07:35:59.242]: Info: Creating encoder [hevc_nvenc]
[2024-09-03 07:35:59.242]: Info: Color coding: SDR (Rec. 709)
[2024-09-03 07:35:59.242]: Info: Color depth: 10-bit
[2024-09-03 07:35:59.242]: Info: Color range: JPEG
[2024-09-03 07:35:59.417]: Info: NvEnc: created encoder HEVC P1 yuv444 10-bit two-pass rfi
[2024-09-03 07:35:59.495]: Info: 
[2024-09-03 07:35:59.495]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2024-09-03 07:35:59.495]: Info: 
[2024-09-03 07:35:59.495]: Info: Found H.264 encoder: h264_nvenc [nvenc]
[2024-09-03 07:35:59.495]: Info: Found HEVC encoder: hevc_nvenc [nvenc]
[2024-09-03 07:35:59.495]: Info: Executing [Desktop]
[2024-09-03 07:35:59.786]: Info: nvprefs: No need to modify application profile settings
[2024-09-03 07:35:59.786]: Info: nvprefs: No need to modify global profile settings
[2024-09-03 07:35:59.801]: Info: WLAN interface 0 is now in low latency mode
[2024-09-03 07:35:59.866]: Info: CLIENT CONNECTED
[2024-09-03 07:36:00.031]: Info: Gamepad 0 will be Xbox 360 controller (default)
[2024-09-03 07:36:00.076]: Info: Selected audio sink: virtual-Surround 7.1{0.0.0.00000000}.{1e1f94cf-9b4b-42c3-a62c-d51546e4e70c}
[2024-09-03 07:36:00.102]: Info: Changed virtual audio sink format to [S32 48000 7.1]
[2024-09-03 07:36:00.148]: Info: Audio capture format is [F32 48000 7.1]
[2024-09-03 07:36:00.154]: Info: Opus initialized: 48 kHz, 8 channels, 2048 kbps (total), LOWDELAY
[2024-09-03 07:36:00.374]: Error: Failed to locate an output device
[2024-09-03 07:36:00.877]: Error: Failed to locate an output device
```

**Comment by ClassicOldSong** [comment]
Can you try with the latest release and post a whole log? There're added information that might help locating the problem.

Does Steam Big Picture stream correctly when started manually?

**Comment by ClassicOldSong** [comment]
Just briefly checked Moondeck's code:

I don't have a deck, I hacked its code to simulated the moondeck's working process. It seems that you have to set the app `MoonDeckStream` with the correct display settings, enabling virtual display for it. In this case, leave all parts blank, no do/undo commands for display changes, no display management in MoondeckBuddy, since Apollo already handled resolution matching and set the virtual display as default.

If you don't care anything about streaming your physical monitor, just go to `Audio/Video` tab and enable `Headless Mode`. If you can't make sure which graphics card the virtual display is using, fill the `Adapter Name` to your desired graphics card. Save then reboot your computer.

**Comment by ClassicOldSong** [comment]
Is this issue fixed now?

**Comment by KoikazeJunsei** [comment]
I can't speak for the other guy, but I can't seem to get it to behave properly.  it seems to still want to change resolutions without using the virtual display and then pops big picture up on the main monitor and leaves me with a normal desktop view on the steam deck.  I have headless enabled, always use virtual display, and enforce virtual display primary.  Any ideas?

**Comment by ClassicOldSong** [comment]
@KoikazeJunsei can you post a screenshot of your Audio/Video tab and configuration of the MoonDeckStream app?

Does virtual display setup correctly when starting with other clients?

**Comment by ClassicOldSong** [comment]
Any update?

**Comment by KoikazeJunsei** [comment]
Sorry for the delay, every time I thought about it, I was at work without access to my pc.   When I use virtual display or even plain desktop everything is fine and it uses the virtual display, it only seems to have issues with steam big picture opening on the wrong display.
[Apollo.pdf](https://github.com/user-attachments/files/17217782/Apollo.pdf)
[Apollo2.pdf](https://github.com/user-attachments/files/17217786/Apollo2.pdf)

**Comment by ClassicOldSong** [comment]
What version of Windows are you using? Setting display to primary is broken in Windows11 24H2 so you have to manually do it once in Windows settings. Disabling your physical display while streaming with virtual display will most definitely force it to the virtual display.

I can't remember if Steam Big Picture has config about which display to use but it's worth checking if you have set it to your physical display somehow.

**Comment by ClassicOldSong** [comment]
Just checked, there is a `Preferred display` option on Big Picture Mode

![image](https://github.com/user-attachments/assets/d89bfabe-add2-451e-91d3-80bf7b977844)

**Comment by KoikazeJunsei** [comment]
I'll check that when I get home, thanks!

**Comment by KoikazeJunsei** [comment]
This seems to have fixed the issue. It was indeed set to preferred monitor.
Everything else is working great!

**Comment by justin-delano** [comment]
Hi, I am trying to get moondeck set up with apollo! How do I configure MoonDeckStream to launch a game? Currently it just sends me to the desktop with no controller support. Thanks!

**Comment by ClassicOldSong** [comment]
@justin-delano If I have understand their code correctly, you don't need to start MoonDeckStream manually while using Moondeck, just launch games directly from Moondeck should be fine. The MoonDeckStream app is added there for starting the stream only, and the app is launched through a separate channel managed my MoondeckBuddy.

**Comment by justin-delano** [comment]
Hmm I am having another issue then, since I get the error "Failed to find application MoonDeckStream"

**Comment by ClassicOldSong** [comment]
It's said that there's setup instructions within the plugin itself. Have you followed the instructions?

> It requires an additional lightweight app to be installed on the host PC - [MoonDeck Buddy](https://github.com/FrogTheFrog/moondeck-buddy). Additional one-time setup instructions can be found within the settings page of the plugin itself.

**Comment by justin-delano** [comment]
I do have MoonDeck Buddy installed, and seemingly both Apollo and MoonDeck buddy are paired to my Deck. Moonlight in desktop mode also works with Apollo, so it's definitely either a moondeck issue or a issue on my end (likely the latter)!

**Comment by ClassicOldSong** [comment]
It looks like you'll have to manually add an app named "MoonDeckStream" and launch a utility called `MoonDeckStream.exe`.

I don't have a Steam Deck so the usage is purely deduced from the code itself, it might not be accurate, so if you're still having issues with Moondeck's usage, it's better consulting the creator of Moondeck directly.

**Comment by justin-delano** [comment]
You're totally right! I didn't read this sectiion until now:
https://github.com/FrogTheFrog/moondeck-buddy/wiki/Sunshine-setup
And I should have! It seems to be working!

**Comment by ClassicOldSong** [comment]
It seems moondeck buddy can connect to Apollo without problems. Closing this issue now.

**Comment by DeadEndRoad87** [comment]
Running into some similar trouble as this thread I think. For the life of me I can't get my Steam Deck to work with Apollo with Moonlight, with or without MoonDeckBuddy. I tried to replicate the steps in the thread but Moonlight either doesn't show any apps in the menu (including Big Picture/Desktop), or with DeckBuddy, cannot find MoonDeckStream despite being pointed to the .exe as an app in Apollo's web ui.

I do know that MoonDeckStream's pathing is working, as it does show up and function through my Android client. 

The deck has been given full permissions, same as my Android device.

Here's my most recent log. Hopefully it's useful.
[sunshine.log](https://github.com/user-attachments/files/17608932/sunshine.log)

**Comment by ClassicOldSong** [comment]
From your log, MoonlightBuddy launched sueecssfully, and the stream started normally and received some controller input. So What's the actuall problem?

One thing I noticed is that the FEC percentage keeps going up, indicating that you have a bad network connection. Or maybe you need to upgrade the Moonlight client on your Deck to the very latest Linux version.

**Comment by ClassicOldSong** [comment]
Ah ok it's your Android client launching the app

So probably it's the Moonlight on your steamdeck being a bit old and not able to handle some custom fields I added into Apollo. Try upgrade the client and see if it works.

**Comment by DeadEndRoad87** [comment]
> Ah ok it's your Android client launching the app
> 
> So probably it's the Moonlight on your steamdeck being a bit old and not able to handle some custom fields I added into Apollo. Try upgrade the client and see if it works.

I have the 6.1.0 flatpak which looks to be the latest version. To be thorough I've re-installed it. I tried the appimage as well. Same behavior is happening. If there's another version to try I can give that a go.

Here's what happens after I pair to Apollo. There are no apps in the menu in Moonlight after selecting my host PC.

If I try to use MoonDeck instead, it will launch MoonDeck Buddy on my host PC, change the desktop resolution, but on the deck will give me this "loading app list" screen then after a few seconds the "failed to find application MoonDeckStream" error.

![7_2](https://github.com/user-attachments/assets/d293d355-a6f4-422e-8ca4-5c06d3661157)
![10933203_4](https://github.com/user-attachments/assets/fbd72d1f-684b-46e5-8850-a4f8734be46a)
![10933203_3](https://github.com/user-attachments/assets/480f7a27-f89a-4331-8fe3-2922d4a5949f)

**Comment by ClassicOldSong** [comment]
App launched through Moondeck is actually launched by MoondeckBuddy. If you want to use Apollo's virtual display feature you should let Apollo handle the display creation, so you need to disable Moondeck's resolution change. Other than that I don't think there's anything different that could cause the issue.

I have tried on a desktop linux machine and 6.1.0 flatpack could correctly find and connect to my Apollo host. You might need to check logs from Moolight to find what's actually happening.

**Comment by DeadEndRoad87** [comment]
I wasn't even aware Moondeck was going to touch resolution. This is my first time using it, was just looking for any kind of solution for Moonlight not working and found this thread lol.

In the meantime I will look at some logs and continue to use Artemis, which works beautifully. Thanks for taking a look!
