### ISSUE TITLE
night mode does not apply to virtual monitor

### ISSUE THREAD

**Issue by AmplificPanda** [ClassicOldSong/Apollo#32]
I am a night time gamer and love night mode on everything, unfortunately even tho it is applied to the virtual display in settings, it doesn't seem to be active?

**Comment by AmplificPanda** [comment]
seems to completely disable night mode on all displays when virtual is connected

**Comment by ClassicOldSong** [comment]
Night mode is not captured. You may enable night mode on your client device instead.

**Comment by AmplificPanda** [comment]
Is this a limitation of the virtual monitor? Client device does not have option of night mode (Samsung dumb tv)

**Comment by ClassicOldSong** [comment]
It actually should be a design choice by Sunshine. Night mode are usually achieved by adjusting Chroma parameters of a monitor, which is deliberately ignored by Sunshine as it might make color rendered on clients wrong as clients have their own Chroma settings for their own screen.

You may have noticed that when night mode is enabled, the tint isn't included in any of your screen shots taken from the computer itself.

I might be wrong in some details but the basic concept is there. You can try some third party night mode apps that work by creating a tinted overlay, or get a pair of blue light filtering glasses.

**Comment by AmplificPanda** [comment]
Will there be a future option to force Sunshine to override chroma of clients?

**Comment by ClassicOldSong** [comment]
Chroma is required for color calibration for screens so no, providing an option to disabling it may result in more confusions.

What client are you actually using? The Tizen one or the Android one?

It's recommended to get a Android box/HTPC connected through HDMI to your TV no matter what your system your TV comes with, you can have much higher freedom of configurations than using Moonlight directly on TV.

**Comment by AmplificPanda** [comment]
Tizen tv, i do have a SHIELD, but even that provides no option to really make the colors similar to the night mode of windows 11.

**Comment by ClassicOldSong** [comment]
Then you can try installing some third party night mode apps on your Shield. Since it's Android, you can do whatever you want on it.
