### ISSUE TITLE
Running two instances of apollo

### ISSUE THREAD

**Issue by Nenterro** [ClassicOldSong/Apollo#33]
Like the title says I want to run two instances of apollo for a dual monitor solution. How can I do this.

**Comment by ClassicOldSong** [comment]
Check out https://github.com/ClassicOldSong/Widecar#advanced-usage

Just don't add the prepare commands, all other processes are the same despite changing Sunshine references to Apollo.

**Comment by ClassicOldSong** [comment]
Added a dedicated instruction in the Wiki: https://github.com/ClassicOldSong/Apollo/wiki/How-to-start-multiple-instances-of-Apollo
