### ISSUE TITLE
Functionaility of 2 apollo/sunshine clients

### ISSUE THREAD

**Issue by challi1337** [ClassicOldSong/Apollo#34]
I was wondering if it is possible to add some kind of "multiplayer" functionality to being able to run 2 apollo/sunshine clients via widescreen. I set it up but sadly controls and audio overlaps between the clients and applications.

I tried logging a different user and starting one instance there and another on my main user but sadly could not connect on the user thats not currently logged into the pc. 

Is it possible to add functionality like that? So that 2 people could be using the pc at the same time

**Comment by ClassicOldSong** [comment]
That's not possible with current code structure. Maybe you're looking for Duo?

**Comment by challi1337** [comment]
Good to know and thanks for the fast response. Yea I was just looking at Duo and Whales/Wolf as solutions for that, would've preferred it over regular apollo/sunshine though

**Comment by ClassicOldSong** [comment]
As a side note, home/professional edition of Windows usually don't support multi user using RDP simultaneously as well. Duo seems achieved multi user using RDP API but there're limitations like some games refuse to launch with Duo and hibernation are reported broken.

**Comment by challi1337** [comment]
Yes I've used RDP this way before "rdpwrapper" enabled it then, but performance was just much worse than streaming over apollo/sunshine and don't wanna go back to that, I'll give free duo a try to see if all works fine before perhaps upgrading.
Thanks to your efforts and enhancements to sunshine.

**Comment by ikeelz** [comment]
[challi1337](https://github.com/challi1337), скажи пожалуйста что у тебя по итогу вышло?
К какому решению ты по итогу перешел?
