### ISSUE TITLE
Prep commands not working with virtual display 

### ISSUE THREAD

**Issue by hassanhabbak** [ClassicOldSong/Apollo#37]
Hey hey!

Great work so far it’s amazing!

One thing missing is that the prep commands that fires before and after streaming don’t apply to virtual display. I usually use them for starting playnite in full screen but nothing. 

I also noticed that virtual display is not treated like an application so no way to add commands to it as well.

**Comment by ClassicOldSong** [comment]
You can add another desktop entry with and have "Always use virtual display" checked. Then you can customize the prep commands.

**Comment by hassanhabbak** [comment]
That did the trick many that’ thanks!!
