### ISSUE TITLE
Windows Defender detecting trojan on the Apollo file

### ISSUE THREAD

**Issue by Shally1986** [ClassicOldSong/Apollo#38]
On downloading the Apollo executable repeatedly defender is blocking and complaining of  virus/trojan.

Is the file safe or affected with Virus ?

![image](https://github.com/user-attachments/assets/ce84fb24-c32a-4c70-8490-ab5274598f76)

**Comment by ClassicOldSong** [comment]
> [VirusTotal scan report for this build](https://www.virustotal.com/gui/file/65748a5f30839d4753743d74e06640e37769b9d1276d836446bb5a6f5beb526c)
>
> [Why Windows always report file as harmful?](https://github.com/ClassicOldSong/Apollo/issues/21)

**Comment by prom3theu5** [comment]
Gotten worse now, the latest version defender blocks the download, as well as removes the exes if you open the explorer folder

**Comment by ClassicOldSong** [comment]
Windows Defender detects no issue with the latest build: https://www.virustotal.com/gui/file/33bc8d7e3db89708dab3ebeac47738292b9c141aad64a3102b305bef8364c01e

It's just being way too defensive. Add exception to the downloaded file should stop it being removed.
