### ISSUE TITLE
v0.2.0-alpha.1 - Pairing Issue

### ISSUE THREAD

**Issue by sickypedia** [ClassicOldSong/Apollo#40]
The latest alpha with the revamped permission system fails to work with legacy Moonlight client (Windows 11 x64) 6.0.1, works on Artemis on my phone. Pairing works, but starting a stream results in "Permission denied Error 503". Reverting to v0.1.4-alpha.2 solves the issue.

**Comment by sickypedia** [comment]
@ClassicOldSong tagging for visibility

**Comment by ClassicOldSong** [comment]
That means the permission system works. Go to the PIN tab and grant Launch permission for your newly paired device. View permission can only join an already launched stream.

**Comment by sickypedia** [comment]
Thanks for clarifying! Was able to connect after setting the launch permission.
