### ISSUE TITLE
是否可以让用户权限管理的键盘权限与鼠标权限分开设置

### ISSUE THREAD

**Issue by Efinaa** [ClassicOldSong/Apollo#45]
全局设置里面的键盘权限和鼠标权限也是分开设置的

**Comment by ClassicOldSong** [comment]
分开键鼠权限从安全性角度上来说没有意义，这个选项是防止远程同乐的时候对方误操作键鼠用的。

目前输入权限再细分的话会有些太琐碎了。

**Comment by Efinaa** [comment]
我也是和朋友远程同乐，只需要键盘操作，但是朋友动鼠标的话主机的鼠标也会动，只能全局关闭鼠标，但是这样的话我远程也不能控制鼠标了

**Comment by ClassicOldSong** [comment]
已加，下一个release就有了

**Comment by ClassicOldSong** [comment]
https://github.com/ClassicOldSong/Apollo/releases/tag/v0.2.2-alpha.1

因为涉及到权限配置变更，所以为此单开了一个release
