### ISSUE TITLE
关于Apollo的键盘以及鼠标捕获问题

### ISSUE THREAD

**Issue by zzyhhh114514** [ClassicOldSong/Apollo#46]
系统：macOS12.7.4
moonlight版本：官方版6.1.0
问题描述：在串流时无法捕获触控板和键盘的操作，按了多次control+shift+z切换模式仍然不管用，系统光标在点击moonlight串流画面后消失，切换到Windows的光标但仍然无法移动，键盘的快捷键也无效，已确认Windows处于运行状态，在Artemis上操作一切正常，尝试过重启mac和Apollo客户端，外接鼠标均无效，在使用基地版时未出现此问题

**Comment by ClassicOldSong** [comment]
去PINtab下给对应设备增加键盘鼠标输入权限
