### ISSUE TITLE
Artemis: Host PC returned error: Permission denied (Error code: 503)

### ISSUE THREAD

**Issue by luyunyu** [ClassicOldSong/Apollo#47]
Firstly, I want to express my gratitude for your contributions to the open-source community. I'm encountering an issue where I can successfully connect to the first device, but when attempting to connect to the second device, I receive the following error: "Artemis: Host PC returned error: Permission denied (Error code: 503)". Could you please assist with this?

**Comment by ClassicOldSong** [comment]
https://github.com/ClassicOldSong/Apollo/wiki/Permission-System

**Comment by ClassicOldSong** [comment]
You need to grant "Launch Apps" permission for newly paired devices in order to start streaming from them, otherwise they'll only be able to join existing streams.

**Comment by luyunyu** [comment]
I understand, thank you.
