### ISSUE TITLE
Can't use my ipad as a secondary screen

### ISSUE THREAD

**Issue by cdguy** [ClassicOldSong/Apollo#53]
Hello,
First of all thank you for the project, the response time between the two secreens is lightning fast :)

However, I have an issue

As I am using a windows machine, I would like to use my ipad as a secondary screen

When I use Apollo, I can only mirror my PC screen to my iPad

And, I can't see "1|2 in my Windows settings"

Thanks for the help!

**Comment by ClassicOldSong** [comment]
Which entry are you clicking on your iPad?

**Comment by cdguy** [comment]
> Which entry are you clicking on your iPad?

![IMG_0100](https://github.com/user-attachments/assets/a2876d3f-f374-47cb-9b98-558dc2f03334)

**Comment by ClassicOldSong** [comment]
You have to click Virtual Display, or configure Desktop with "Always use virtual display" enabled in Apollo's WebUI.
