### ISSUE TITLE
偶尔会画面卡顿，只有声音【bug】

### ISSUE THREAD

**Issue by ZhaoZelin2000** [ClassicOldSong/Apollo#59]
这是moonlight连接画面卡顿的截图，此时只有声音![Snipaste_2024-10-01_14-46-31](https://github.com/user-attachments/assets/f2ce6b6a-d3ff-4bfa-b45f-a1de2aa81e73)
这是rustdesk的画面，是正常的。
![Snipaste_2024-10-01_14-46-20](https://github.com/user-attachments/assets/edb9ba1b-bd6d-4be4-9fbb-d6e4ecd9cc55)

**Comment by ClassicOldSong** [comment]
把调试信息打开，卡顿时截图
可能是你码率开太高而网络/设备跑不动了

**Comment by ClassicOldSong** [comment]
有任何进展吗？

**Comment by ZhaoZelin2000** [comment]
> 有任何进展吗？

现在偶尔还是会遇到这个问题，我只能通过重启Apollo解决

**Comment by ClassicOldSong** [comment]
请把调试信息打开，卡顿时截图

**Comment by ZhaoZelin2000** [comment]
> 把调试信息打开，卡顿时截图 可能是你码率开太高而网络/设备跑不动了

卡顿时，我无法打开调试信息，此时ctrl+alt+shift+q，ctrl+alt+shift+m等可以使用，ctrl+alt+shift+s没有反应

**Comment by ClassicOldSong** [comment]
返回菜单也不行吗？你也可以打开Lite模式常驻，卡顿时直接截图

**Comment by ZhaoZelin2000** [comment]
> 返回菜单也不行吗？你也可以打开Lite模式常驻，卡顿时直接截图

好的，我晚上尝试一下看能不能复现

**Comment by ZhaoZelin2000** [comment]
我最近没有遇到这个问题，上次遇到似乎与显卡长时间高负载工作相关。有新的进展我会及时反馈

**Comment by ClassicOldSong** [comment]
我不清楚Rust Desk是否也在使用GPU编码，如果不是那在GPU高负载时CPU编码保持流畅也是有可能的。下次遇到的时候麻烦也报告一下系统配置信息，这个issue先关掉了。

**Comment by ZhaoZelin2000** [comment]
![image](https://github.com/user-attachments/assets/4500102e-b7b5-47c3-92f5-2d5fcd4b0b80)
显示图形驱动崩溃，这可能是因为我使用13代cpu导致的。因为我在其他游戏中也遭遇到画面卡顿，图形驱动崩溃。

**Comment by ZhaoZelin2000** [comment]
> ![image](https://private-user-images.githubusercontent.com/72080838/377337224-4500102e-b7b5-47c3-92f5-2d5fcd4b0b80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNDY2MjksIm5iZiI6MTcyOTE0NjMyOSwicGF0aCI6Ii83MjA4MDgzOC8zNzczMzcyMjQtNDUwMDEwMmUtYjdiNS00N2MzLTkyZjUtMmQ1ZmNkNGIwYjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDA2MjUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNThlOTcyNmVlYjQ4YzA5Y2MyMDM5M2ViMDY4YmI2NGY2ODJlNjRlNGRiZGFjYWI3NDAwZTQ5MmNkMzlkNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3A41HIJTl1Nz25v5lwyF_AJaa5ii0I9lJIgmi4JMy5s) 显示图形驱动崩溃，这可能是因为我使用13代cpu导致的。因为我在其他游戏中也遭遇到画面卡顿，图形驱动崩溃。

我按照提示perform a clean install后还会遇到，可能于13代cpu不稳定有关

**Comment by ClassicOldSong** [comment]
13代CPU那可能除了换电脑以外无解了。。。。
