### ISSUE TITLE
[Feature Request] Set Windows UI scaling on virtual display

### ISSUE THREAD

**Issue by JeffSchofield** [ClassicOldSong/Apollo#60]
Hello! Obligatory thank you so much for your time and effort on this fork. I just picked up the latest Galaxy tablet and discovered this while searching for a solution to the niche trackpad scrolling issue. I am focused equally on remote desktop and gaming.

I was wondering what the effort would be to implement support for setting UI scaling on the virtual display based on what is requested by the client?

On the Tab S10 Ultra, the native resolution combined with the virtual display feature works like a dream, except for how small the UI becomes.

I know there is a resolution scaling option, and apologies in advance if I am misunderstanding this feature, but it doesn't seem to accomplish the same thing as UI scaling. If I set this option to 200%, the UI becomes even smaller. If I set it to 50%, the UI becomes bigger but the image comes out fuzzy. I believe this has more to do with the relationship between the virtual monitor and the video stream rather than the UI scaling. 

I've only recently dipped my toes into this level of development for Windows so I'm not sure I can be of much help, but if you're busy working on other things and can point me in the right direction, I wouldn't mind taking a stab at adding support.

Thanks again!

**Comment by ClassicOldSong** [comment]
The UI scaling feature is for resolution scaling, for super/subsampling purpose.

If you want to specify the Windows UI scale factor per-device, just adust them in the Windows settings. Windows will remember them per-device with Apollo.
