### ISSUE TITLE
iOS SSL problem

### ISSUE THREAD

**Issue by ustix** [ClassicOldSong/Apollo#61]
It is a Moonlight client problem, but it is present here too: if you are using a custom certificate (RSA-2048) you can't pair an iOS device. Can someone try to address that problem? I just get a "Pairing Failed" error, but nothing else.

**Comment by ustix** [comment]
By "mistake" i have found a solution for my problem. Somehow if you change the default ports to something else (I have changed it to 48990 instead of 47990) and you use the given port with adding your pc manually, it is suddenly working on iOS too, with SSL, even over VPN (i'm using zerotier)

**Comment by ClassicOldSong** [comment]
Might be related to client side caches, not sure. Will investigate this problem when I start working on an iOS fork. Closing this issue as resolved now.
