### ISSUE TITLE
Log Spam - "Unable to find MAC address" for Tailscale/VPN

### ISSUE THREAD

**Issue by sickypedia** [ClassicOldSong/Apollo#63]
I am using Tailscale to create wireguard tunnels and gamestream over the internet - I'm not sure why Apollo/sunshine would need to flag that a MAC is missing on the virtual tailscale address being assigned, it continuosly spams the log. Is this something that needs fixing, potentially to retain useful info in the logs and prevent any performance hit (even if tiny).

<img width="762" alt="{742A15BD-B42B-4AE4-AE9C-D14848FC9ECB}" src="https://github.com/user-attachments/assets/3e9017cb-dcde-4b45-b93f-a4d9869a1c87">

**Comment by ClassicOldSong** [comment]
MAC address is reported to clients for WOL purpose. A virtual interface won't be able to WOL, so the log is not really useful. Maybe lowering the log level to debug will be better.

**Comment by sickypedia** [comment]
I see, thanks!
