### ISSUE TITLE
[Issue]: 上传剪贴板中文乱码

### ISSUE THREAD

**Issue by hitopo** [ClassicOldSong/Apollo#69]
### Describe the bug

Apollo和Artemis都是最新的版本

步骤：
1. 提前在串流机器上复制中文
2. 上传剪贴板到被串流PC上
3. 粘贴

粘贴出来的中文是乱码

串流机器：Android，Redmi note 12 turbo
被串流机器：PC，Windows 11Pro 23H2

### Steps to reproduce

![6e8b7a8f16d178ae3e52bfa4691ceee](https://github.com/user-attachments/assets/fd306479-5ab7-4def-b007-d88ddec06f6b)

### Other Moonlight clients

None

### Moonlight adjusted settings

None

### Moonlight default settings

Yes

### Gamepad-related connection issue

Yes

### Gamepad-related input issue

Yes

### Gamepad-related streaming issue

Yes

### Android version

Android 12 

### Device model

Redmi note 12 turbo

### Server PC OS version

Windows 11 Pro 23H2

**Comment by ClassicOldSong** [comment]
应该修好了，试试看？

https://github.com/ClassicOldSong/Apollo/releases/tag/v0.2.4-alpha.2

**Comment by hitopo** [comment]
可以了，感谢！
