### ISSUE TITLE
When i prefer quicksync to encode game performance drop.

### ISSUE THREAD

**Issue by FelixzP** [ClassicOldSong/Apollo#77]
I don't know why it's happened I just set adapter Name to Intel(R) UHD Graphics 630 And \\.\DISPLAY1 play genshin on Artemis give fps around 35-50 on mobile but if i use amd gpu to encode it give better fps.

**Comment by ClassicOldSong** [comment]
You have to start your game on high performance GPU.

**Comment by ClassicOldSong** [comment]
Also, if you're using virtual display, please don't specify display name.

**Comment by FelixzP** [comment]
Now I set to start my game on high performance GPU and don't specify display name have got same result don't know why but i can just use amd to encode. thank you for answer my question

**Comment by ClassicOldSong** [comment]
Oh, i didn't noticed that your using UHD630

It's not that capable of encoding so just use your dgpu.

**Comment by FelixzP** [comment]
Thanks i will use dgpu to encode.
