### ISSUE TITLE
Phew question 

### ISSUE THREAD

**Issue by WesleyVanNeck** [ClassicOldSong/Apollo#8]
Is linux gone be suported and what's planned in this fork

**Comment by ClassicOldSong** [comment]
Linux support should stay untouched for now, maybe some minor changes will be made alongside Windows support but they're not breaking anything at the moment.

What's planned (for both Windows and Linux):
1. Built-in virtual monitor support (Windows driver development on going)
2. Multi monitor streaming from one instance
3. Better audio routing for multi monitor scenarios
4. Trackpad input emulation
5. UI rewrite
6. (Maybe) built-in remote USB support via USB-IP
7. (Maybe) complete refactor (current code is really messy, hardcoding and global variables are everywhere making its maintainability almost 0 to new comers)

What's not planned:
1. Continue macOS support (for their limited screen capture capabilities and huge delay for third party apps to capture the screen)

**Comment by gibarel1** [comment]
Just here to say that USB/IP would be a huge addition for games like league/valorant, since they block the virtual mouse inputs.

**Comment by NiiightmareXD** [comment]
@ClassicOldSong Is USB-IP added yet? Do you think I can help in any way?
