### ISSUE TITLE
Virtual display not encoding/rendering on dgpu (nvidia)

### ISSUE THREAD

**Issue by playashu** [ClassicOldSong/Apollo#82]
The headless option is not working for me, but found a way to force render the virtual display on Nvidia dgpu. 

1st I have to manually enter the dgpu name in Adapter Name under Audio/Video setting then restart (at this point artemis fails to auto create a virtual display). Then I have to remove the adapter name from the configuration.  After that virtual display start encoding and render through my dGPU which automatically feels much superior in quality. I have confirmed the same form task manager performance stats.

**Comment by ClassicOldSong** [comment]
This is rare but it does happen on some systems. Headless itself doesn't specify GPU backend for virtual display creation, you have to use Headless Mode and specify the adapter name at the same time for it to work.

You can also add a string entry named `gpuName` with the value of the name of your dGPU to `\HKEY_LOCAL_MACHINE\SOFTWARE\SudoMaker\SudoVDA` with `regedit`, this will force the virtual display driver to use the dGPU you have specified. If the path doesn't exist, just create it manually.

After you have done, quit Apollo and reload the driver or restart your computer.

**Comment by playashu** [comment]
Not able to find the specified path on my end registry editor.
