### ISSUE TITLE
服务启用之后 经常性出现无法连接到moonlight 只能重sunshine解决

### ISSUE THREAD

**Issue by jinbaix** [ClassicOldSong/Apollo#83]
如题

**Comment by ClassicOldSong** [comment]
网络/防火墙/系统问题

请详细描述PC和客户端之间的网络连接状态

**Comment by jinbaix** [comment]
1、网络环境：双栈公网 通过花生壳解析域名 pc为wifi7网卡、wifi7路由器  客户端通过手机共享网络
2、服务端配置页面能够正常打开 但客户端无法搜索到该pc（不是连接失败 而是搜索不到这台电脑）

**Comment by ClassicOldSong** [comment]
直接公网访问不确定性因素太多了，建议走一层P2P VPN，比如TailScale/ZeroTier

**Comment by jinbaix** [comment]
了解 我周末到家再尝试一下

**Comment by ClassicOldSong** [comment]
有进展吗？

**Comment by jinbaix** [comment]
使用tailscale之后确实解决了问题
可以正常连接 已经弃用花生壳
