### ISSUE TITLE
Working Directory problem with folders including Japanese characters

### ISSUE THREAD

**Issue by Egoistically** [ClassicOldSong/Apollo#84]
Hello, I find myself unable to launch an app whenever I use a Working Directory where a folder name includes Japanese characters. The issue does not occur when I include the full directory in the command rather than using Working Directory, but for some games this is not an option.

Example logs with folder `C:\Games\河原崎家の一族２ 完全版` and executable `AI6WIN.exe`, which lead me to believe the characters are not being read properly:
``Info: C:\Games\河原崎家の一族２ 完全版\AI6WIN.exe running with PID 18996`` - works fine.
``Info: Executing: [AI6WIN.exe] in ["C:\Games\河原崎家の一族！E完偅牁E"]`` - does not work.

Thanks for your time.

**Comment by ClassicOldSong** [comment]
Known issue for Windows. I'll try to fix it in the next update but there's no guarantee it will be fixed since Windows has been known to have lots of issues with file name encodings...

For now can you try to use English only folder names?

**Comment by Egoistically** [comment]
Sure, I will do that for the time being. Thanks a lot!

**Comment by Egoistically** [comment]
Still happens with v0.2.5-alpha.1:
``[2024-10-26 23:37:54.181]: Info: Executing: [AI6WIN.exe] in ["C:\Games\河原崎家の一族！E完偅牁E"]``
``[2024-10-26 23:37:54.182]: Error: Failed to launch process: 2``

**Comment by ClassicOldSong** [comment]
Can you post a more complete log?

**Comment by ClassicOldSong** [comment]
what system language and encoding are you using?

**Comment by ClassicOldSong** [comment]
You might need to share your `apps.json` as well, I can't replicate the half garbling effect on my environment.

**Comment by Egoistically** [comment]
Locale is Japanese without UTF-8 enabled.
[apps.json](https://github.com/user-attachments/files/17534807/apps.json)

**Comment by Egoistically** [comment]
Works with that, thanks a lot!
