### ISSUE TITLE
NVENC Intra Refresh

### ISSUE THREAD

**Issue by woiza** [ClassicOldSong/Apollo#86]
Hi,

could you please take a look at these two issues?

https://github.com/LizardByte/Sunshine/issues/3323

https://github.com/TheElixZammuto/moonlight-xbox/issues/117

Do you have an idea on how this could be solved?

**Comment by woiza** [comment]
@ClassicOldSong thank you very much! I played for about three hours and had no artifacts. I can stream 4k120 with 120 Mbit/s.  Higher bitrates result in stuttering every 30 seconds or so. Using Nvidia Gamestream 150 Mbit/s is possible, but with artifacts.

Do you think intra refresh is better than this fix?

https://github.com/TheElixZammuto/moonlight-xbox/pull/140

**Comment by ClassicOldSong** [comment]
Actually I do. This actually reduced decoding delay further more on my other clients.
