### ISSUE TITLE
多实例锁屏界面无法操作

### ISSUE THREAD

**Issue by yaole-A** [ClassicOldSong/Apollo#87]
第一个默认配置文件的可以在锁屏界面进行操作，第二个指定配置文件的在锁屏界面无法操作，会卡屏，官方的便携版也是这个问题，锁屏界面无法操作，只有安装的版本可以在锁屏界面操作

**Comment by ClassicOldSong** [comment]
你按Wiki里的教程配置多实例了吗

教程里明确说了不用System权限的话会导致锁屏和UAC界面无法操作

**Comment by yaole-A** [comment]
> 你按Wiki里的教程配置多实例了吗
> 
> 教程里明确指出使用系统权限问题会导致锁屏和UAC界面无法操作

直接管理员命令行里面打开的，可以正常使用，只有在按win+l锁屏后第二个实例在无法操作，只有第一个默认配置的可以

**Comment by yaole-A** [comment]
> 你按Wiki里的教程配置多实例了吗
> 
> 教程里明确指出使用系统权限问题会导致锁屏和UAC界面无法操作

没有完全按照教程来，我只是管理员命令行执行sunshine.exe path\to\sunshine_2.conf这个了，我这次完全按wiki来，还下载那个psexec，然后ps1文件管理员执行好了，非常抱歉，我的问题，谢谢了
