### ISSUE TITLE
笔记本混合模式下，Adapter Name指定独显时首页报错但是实际使用正常

### ISSUE THREAD

**Issue by jizni** [ClassicOldSong/Apollo#89]
笔记本混合模式下，不指定Adapter的时候，默认会使用核显进行编码，指定独显之后首页报错，但是串流可以正常使用
![QQ截图20241029103232](https://github.com/user-attachments/assets/dc6a7cd8-2def-4aa3-b3bb-350fb847d21b)
![QQ截图20241029103218](https://github.com/user-attachments/assets/00ac7fa6-5d06-413a-a270-5853c0501f4a)

**Comment by ClassicOldSong** [comment]
在 Audio/Video tab 下打开无头模式即可
