### ISSUE TITLE
how to use postman close apollo app

### ISSUE THREAD

**Issue by yybfrank** [ClassicOldSong/Apollo#90]
I want to close the game use http api,how to do that?

**Comment by yybfrank** [comment]
when I close moonlight client but host app still running and never close it.

**Comment by ClassicOldSong** [comment]
You need to exit the app manually. Closing the client without exiting the app properly will only disconnect the stream.

You can send a POST request to `https://hostip:47990/api/apps/close` to force close the current running app, but you'll need to login first to get the cookies.

But:
1. The server cert is self-signed, which Postman might not like
2. Only one active login session is allowed, and the credential will reset after several days or a restart of Apollo, so if you can't store the cookie for future API calls.
