### ISSUE TITLE
Can't download covers anymore after v0.2.5-alpha.1 build

### ISSUE THREAD

**Issue by CharlieDestroyerOfTacos** [ClassicOldSong/Apollo#91]
Currently running Version v0.2.6-alpha.1 and still seeing this problem.

When adding a new application the interface will no longer allow you to download cover images anymore. You can type the name in the "Application Name" box and then click the "Find Cover (Online)" button and it will display the image results, but clicking on the images does absolutely nothing now. All covers have to be manually downloaded and the path added into the "Image" box by hand.

**Comment by ClassicOldSong** [comment]
Fixed in https://github.com/ClassicOldSong/Apollo/releases/tag/v0.2.6-alpha.2
