### ISSUE TITLE
How to create a virtual screen without a client connection by Apollo

### ISSUE THREAD

**Issue by ZhaoZelin2000** [ClassicOldSong/Apollo#97]
How to create a virtual screen without a client connection, and how to use Apollo to create a virtual screen when I am only using my own PC without a client connection. As you stated, 'It is highly recommended to remove any other virtual display solutions from your system and Apollo/Sunshine config, to reduce conflicts and compatibility issues.'

**Comment by ClassicOldSong** [comment]
Create an empty app, check "Always use virtual display" and launch it from web ui.

**Comment by ZhaoZelin2000** [comment]
Thank you
