### ISSUE TITLE
Can't get resolution to match client

### ISSUE THREAD

**Issue by AlanKK** [ClassicOldSong/Apollo#99]
Host:
- Windows 11
- AMD Radeon RX 7900 GRE
- Physical monitor attached with HDMI is 3440x1440
- Apollo installed

Client Laptop
- Macbook Air 15" with 2880x1864
- Moonlight configured with 2880x1864, 60 FPS, 55 mbps bitrate, vsync on, Fullscreen

I previously had sunshine and vdd installed.  I think I've completely removed them and cleared the cache entries in the registry per the FAQ.  Rebooted, installed Apollo.

I use Microsoft Remote Desktop to connect sometimes as well and it sets the client resolution fine.  But when I login with moonlight, the resolution is 3440x1440 and seems to think it is my physical display.  I can see the SudoMaker VDA in the device manager and don't see any issues there.  What am I missing?

**Comment by ClassicOldSong** [comment]
Check your Windows display settings, and make sure it's not in mirroring mode.

**Comment by AlanKK** [comment]
I can't see the setting.  When I am on the physical display, there is only one monitor so I don't see the mirroring option.  While still on the physical display, I connect with moonlight from my laptop.  I still don't see multiple monitors in display settings and my moonlight session is mirroring the physical and has the same resolution.

**Comment by ClassicOldSong** [comment]
Have you started with the Virtual Desktop entry?

**Comment by AlanKK** [comment]
I don't know.  What do you mean?

**Comment by AlanKK** [comment]
Oh, I see what you mean, using + Virtual Display in moonlight.  That may have fixed it for me.  Thanks!

**Comment by ClassicOldSong** [comment]
You can also configure your app with `Always use Virtual Display`.

Happy streaming!
